# Change these first
owner: d1vanloon # Your GitHub username
repo: family-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: SCARIF
    url: https://scarif.vanloon.family/
  - name: Plex
    url: https://plex.vanloon.family/web/index.html
  - name: VLTV
    url: https://live.vanloon.family/
  - name: S3
    url: https://s3.vanloon.family/minio/login/
    headers:
      - "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.19 Safari/537.36 Edg/90.0.818.6"
  - name: Streaming Ingest
    url: https://ingest.vanloon.family/
  - name: Media Requests
    url: https://requests.vanloon.family/
  - name: MovieMatch
    url: https://moviematch.vanloon.family/

assignees:
  - d1vanloon

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.vanloon.family
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /family-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  introTitle: "Monitor system uptime and status."
  introMessage: Check the status of a service and view historical incidents.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.19 Safari/537.36 Edg/90.0.818.6 upptime/d1vanloon

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
